spring.application.name=corthreads

#configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/corthreads?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

#Paramètres JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update